# configs/transfomers_config.yaml
defaults:
  - _self_

wandb:
  project: algorithmic_reasoning
  name: llama_1B_instruct_flip_flop_10_reg_10_50_len_flip_finetuned_grok

model:
  name: meta-llama/Llama-3.2-1B-Instruct
  load_from_checkpoint: True
  checkpoint_filepath: checkpoints/llama_instruct_flip_flop_finetuned_grok.weights
  is_pretrained: False
  model_configuration:
    attention_probs_dropout_prob: 0.0
    hidden_dropout_prob: 0.0

training:
  epochs: 1
  batch_size: 4
  learning_rate: 5e-6
  device: cuda
  ignore_index: -100
  save_checkpoint: True
  checkpoint_filepath: checkpoints/llama_instruct_flip_flop_finetuned_grok.weights
  optimizer_parameters:
    beta1: 0.95
    beta2: 0.999
    weight_decay: 0.2
  train_dataset:
    generator: FlipFlopGenerator
    generator_parameters:
      seed: 1
      use_instruction: True
      use_few_shot: True
      length: ${as_tuple:10,10}
      use_flip: True
      num_registers: ${as_tuple:2,2}
      generate_attn_labels: False
      apply_chat_template: True
    num_samples: 15000
  val_dataset:
    generator: FlipFlopGenerator
    generator_parameters:
      seed: 0
      use_instruction: True
      use_few_shot: True
      length: ${as_tuple:10,20}
      use_flip: True
      num_registers: ${as_tuple:2,2}
      generate_attn_labels: False
      apply_chat_template: True
    num_samples: 100


evaluation:
  device: cuda
  batch_size: 1
  visualize: True
  name: llama_1B_instruct_finetuned_flip_flop_grok_BIG_OOD
  dataset1:
    num_samples: 1
    generator: FlipFlopGenerator
    generator_parameters:
      seed: 42
      use_instruction: True
      use_few_shot: True
      length: ${as_tuple:10,20}
      use_flip: True
      num_registers: ${as_tuple:2,2}
      apply_chat_template: True
  dataset2:
    num_samples: 500
    generator: FlipFlopGenerator
    generator_parameters:
      seed: 42
      use_instruction: True
      use_few_shot: True
      length: ${as_tuple:100,130}
      use_flip: True
      num_registers: ${as_tuple:2,2}
      apply_chat_template: True

  